micronaut:
  function:
    name: listOpenPullRequests
github:
  token: 56a5f3f4ec20d3298358acaa41c7f8df1ba5d136
  organization: AppDirect
  repositories:
    - aws-connector
    - google-connector
    - docusign-connector
    - autodesk-connector
    - QAAuto
    - AppDirect
    - service-integration-sdk

  users:
    - anshul-jain
    - dmarques10
    - elisandoval
    - esteban-mallen
    - gastontulipani
    - fedesassone
    - carlabarbara
    - max-schulkin

slack:
  token: xoxp-4995230642-388883455908-449907149654-4ef71737f115d1895f766502a4146e81
  channel: eli
